### ISSUE TITLE
Discard Reminder Changes When Value is Empty

### ISSUE THREAD

**Issue by lhwdev2008** [AppDevelopers2021/studia#13]
If you leave the "reminder" field empty and hit "save", an empty string value (`""`) will be saved, like this:

<img width="1312" alt="Screen Shot 2021-12-20 at 11 24 27 AM" src="https://user-images.githubusercontent.com/70620386/146702889-33c638e7-6a9f-4840-824e-11270dd90b3b.png">

**Comment by lee-jongwoo** [comment]
Fixed.
Now when the user submits a memo or reminder with an empty value, changes will be discarded.
(Works in iOS WebView as well)
